### ISSUE TITLE
Normalizing Persian Anomalies

### ISSUE THREAD

**Issue by mmsamiei** [persiannlp/persian-language-models#2]
First of all, I want to thank you because of training Persian BERT. It can help the Persian NLP researcher to train and develop many useful and essential models for a variety of tasks. in addition, it will strengthen the position of Persian among other languages. 

secondly, I have viewed your codes. in the preprocessing section, you only filter paragraphs with specific lengths. but as you know, Persian has many orthography anomalies such using **ي** instead of **ی** or writing **"کتابهای"** or **"کتاب های"**  instead of writing "**کتاب‌های"**. you haven't normalized these anomalies, as a result, after the training tokenizer, we can see these anomalies. for example in tokens' file now we have these tokens: **"های"** and **"هاي"**. do you think that it couldn't make problems for PerBERT later? 

another strange thing is that I can't find token with ZWNJ character in your tokens list. maybe it can be my fault but I think you probably remove them in somewhere of code.

Thank you again for your interest in the Persian language 🙏🥰

**Comment by danyaljj** [comment]
> Thank you again for your interest in the Persian language 🙏🥰

Gurban siza! 

> secondly, I have viewed your codes. in the preprocessing section, you only filter paragraphs with specific lengths. but as you know, Persian has many orthography anomalies such using ي instead of ی or writing "کتابهای" or "کتاب های" instead of writing "کتاب‌های". you haven't normalized these anomalies, as a result, after the training tokenizer, we can see these anomalies. for example in tokens' file now we have these tokens: "های" and "هاي". do you think that it couldn't make problems for PerBERT later? 

You're making a good observation here! There is lots of stuff in the data that are not compatible with the standard Persian. Contrary to your point, I'd argue that one should not clean up the data too much when training BERT. Our goal is to build a language model (BERT, here) that **generalizes to all sorts of tasks with all sorts of writings/styles**. By filtering [nonstandard] patterns (like the ones you mentioned) you will end up with a model that is brittle with respect to these pattern variations (think of a QA system that fails when changing "های" to "هاي"; isn't that a bad behavior?) The bottom-line is:  we want the training data of BERT to be as general as possible. Does that make sense to you? 

The right place to do such filtering/standardizations is when you're building end-task datasets to supervise your system; e.g., when building a dataset to supervise, say, a dialogue system, you'd want it to generate an output that follows well-established standards of the language. 

> another strange thing is that I can't find token with ZWNJ character in your tokens list. maybe it can be my fault but I think you probably remove them in somewhere of code. 

We have it in the vocabulary: https://github.com/danyaljj/farsi-language-models/blob/ab43f5267d39177491a60d9add0a7b3012871b5b/bert_model/perBERT-vocab.txt#L11290 

We also have quite a bit of it in the training data: 
```bash 
$ grep -i "zwnj" all_text_merged_cleaned.txt 
١٣&zwnj سال را ممنوع کنیم متاسفانه نتوانستیم تابعیت کودکان با پدر خارجی را پیش ببریم قرار شد لایحه&zwnj.
&zwnj ای در صندوق&zwnj های بازنشستگی تخصیص اعتبار یا.
&zwnj ام ندارد چون من دارایی یا منافعی خارج از.
&zwnj لایحه مورد اشاره مجددا در دستور کار کمیسیون به ریاست لعیا جنیدی معاون حقوقی رئیس.
&zwnj ها پرهیز نماید آیین&zwnj نامه اجرایی این.
&zwnj های داغدار این عزیزان و خصوصا فرهنگیان.
&zwnj ها زندگی کرده&zwnj اند و یا آواره.
&zwnj های غیرقانونی آمریکا و نیز عنایت.
&zwnj ها و کلاس&zwnj های مختلف در.
احکام دائمی برنامه&zwnj های ترخ ۰۹ /۱۲ /۱۳۹۵ هیئت امنا دانشگاه تربیت مدرس.
اختیارات هیئت امنای صندوق می باشد &zwnj مورد.
ادامه جلسه به پیشنهاد برنامه و بودجه کشور آیین&zwnj.
ایران با این در نظام بین&zwnj الملل سازگار نیست.
از روحی روانی مناسب عدم سوءپیشینه و آسیب&zwnj های.
استان&zwnj های و حضور پرشور مردم &zwnj اظهار داشت.
است بانک&zwnj هایی که در آنها سهام دارد نیز.
استفاده از ویتامین و بافت&zwnj ها تغذیه می&zwnj.
اموال غیرمنقول دستگاه&zwnj های اجرایی و ماده ۶۹ پیشنهاد مربوط را جهت سیر.
انرژی کیهانی به صورت طبیعی از طریق چاکراها به بدن منتقل می zwnj;شود و انرژی لازم برای فعالیت zwnj;های بدن را تامین می zwnj;کند.
این کتاب پرفروش ترین کتاب آمازون در سال 2013 در حوزه کارآفرینی است و یک رویکرد نو برای راه zwnj; اندازی کسب وکار ارائه می کند.
به اذعان ایجاد شهر استارت&zwnj آپی ایجاد اشتغال.
به اذعان البرز ایجاد شهر استارت&zwnj آپی ایجاد اشتغال.
به استناد تبصره ۵ ماده ۶۹ درخواست شهرداری بیله&zwnj سوار درخصوص صدور مجوز.
به اینکه در حال حاضر دفاتر خدمات فعالیت می&zwnj نمایند ولو با استدلال صادرات.
بهداشت &zwnj درمان و آموزش نیرو راه و شهرسازی.
به گزارش پایگاه اطلاع&zwnj.
به گزارش پایگاه اطلاعرسانی جامعه&zwnj.
به گزارش « پایگاه اطلاع رسانی دفتر هیئت دولت» به استناد ماده ۷ آیین&zwnj نامه مستندسازی.
به گزارش « پایگاه اطلاع رسانی وزیران به تصویب رسیده بود برای اجرا به وزارت&zwnj.
به گزارش روابط عمومی و امور بینالملل پژوهشگاه فضایی ایران، سازمان همکاریهای فضایی آسیا و اقیانوسیه (اپسکو)، دومین جلسه گروه کارشناسان در زمینه "بررسی امکان&zwnj.
به نرخ مرجع قیمت&zwnj گذاری و توزیع شده&zwnj.
به واسطه تلاش&zwnj ها و خدمات وزارت امور.
پژوهش حاضر با هدف پیش&zwnjبینی کیفیت زندگی زنان متاهل بر اساس دانش و نگرش جنسی و صفات شخصیت انجام گرفت.
ترتیب به عنان استانداران گلستان یب یکی از آیین نامه&zwnj های اجرایی.
تسهیلات ارزان قیمت به وزارت&zwnj خانه های جهاد کشاورزی.
تعجب می&zwnj کنیم که مرکزی مثل مرکز که به صورت ملی تعریف شده طرح هایی می.
تقدیم حضور می گردد ادامه بررسی پیش نویس « خدمات عمومی» پیش&zwnj نویس لایحه.
توضیحات پی zwnj;اچ zwnj;پی (به انگلیسی: PHP) یک زبان برنامه zwnj;نویسی است که برای طراحی وب توسعه یافته zwnj;است، اما می zwnj;توان از آن به عنوان یک زبان عمومی نیز استفاده zwnj;کرد.
توضیحات کتاب ldquo;Why Smart People Can Be So Stupid rdquo; یک بررسی پژوهش zwnj;های روانشناختی است تا آنچه که می zwnj;تواند به ما درباره حماقت در زندگی روزمره بگوید را آشکار می zwnj;سازد.
جهانی پیرامون توثیق اموال مشتریان نزد نک&zwnj ها و موسسات.
چتر حمایتی بیمه&zwnj های تأمین قرار گرفته&zwnj اند که.
چن مقاله و کار علمی می&zwnj طلبد آنچه به بهانه.
چین و کوبا ترکیبی بودند از &zwnj های سوسیالیستی.
حفظ جاذبه گردشگری مناطق کشور را یکی از مسئولیت&zwnj.
حقوقی رئیس&zwnj جمهور توافق&zwnj های بین المللی و محوله اقدام و مراحل.
خسارات ناشی از تصادف بر عهده یا دولت می &zwnj باشد رئیس.
دانلود کتاب خستگی zwnj; و ناتوانی zwnj; جنسی zwnj; +pdf نویسنده zwnj; ن zwnj;.
دانلود کتاب نایاب المراجعات به تعداد 467 صفحه pdf المراجعات یا المراجعات رهبری امام علی در قرآن و سنت یکی از کتب شیعه zwnj;است که توسط عبدالحسین شرف الدین موسوی نوشته شده zwnj;است.
```

Feel free to let me know if you have any other thoughts/suggestions.

**Comment by mmsamiei** [comment]
Thank you for your comprehensive explanation. after your comment, my opinion changed about the **training language model (BERT, here) that generalizes with all sorts of writings/styles.**. I'm convinced that we should have all of "کتاب‌ها", "کتابها" and "کتاب ها"  forms in our dataset for training. 

But about character anomalies such as "ی"  and "ي", I still have a different idea. we can easily correct them without losing any information while having 100% accuracy.  I think that keeping the false format of "ی" which is "ي" can increase repetitive words in our tokens list (which can prevent producing other tokens) and also may result in producing different embedding for one word with two forms for example "آبی"  or "آبي". 

But ultimately I'm sure that you have more experience and knowledge than me and each decision which you will make probably produce a great result. 😊😊😊
